version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "laruno/backoffice-api-dev:latest"
    container_name: client-api-dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "7000:7000"
