version: "3.7"

services:
  backoffice-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "laruno/backoffice-api:latest"
    container_name: backoffice-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "7000:7000"
